Repository oqtopus-team/oqtopus-cloud, pull requests merged in 2024-12, with the labels that each got.

#62 ci: uploading coverage to Codecov
  .github/workflows/python-ci.yaml
  .gitignore
  backend/Makefile
  poetry.lock
  pyproject.toml
Labels: ci

#64 [Docs] Update OpenAPI specification for jobs
  docs/en/architecture/quantum_jobs_in_detail.md
  docs/en/architecture/sequence_diagram.md
  docs/en/index.md
  mkdocs.yaml
Labels: documentation

#61 feat: add pagination get jobs
  backend/oas/provider/openapi.yaml
  backend/oas/provider/paths/jobs.yaml
  backend/oas/provider/schemas/jobs.yaml
  backend/oas/user/openapi.yaml
  backend/oas/user/paths/jobs.yaml
  backend/oas/user/schemas/jobs.yaml
  backend/oqtopus_cloud/provider/routers/jobs.py
  backend/oqtopus_cloud/provider/schemas/jobs.py
  backend/oqtopus_cloud/user/lambda_function.py
  backend/oqtopus_cloud/user/routers/jobs.py
  backend/oqtopus_cloud/user/schemas/jobs.py
  backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
  backend/tests/oqtopus_cloud/user/routers/test_jobs.py
  docs/oas/provider/openapi.yaml
  docs/oas/user/openapi.yaml
  poetry.lock
  pyproject.toml
Labels: documentation, chore, feature, refactor, test

#63 feat: Make API Authorizer pluggable
  docs/terraform_modules/api-server/README.md
  terraform/service/modules/api-server/README.md
  terraform/service/modules/api-server/main.tf
  terraform/service/modules/api-server/variables.tf
  terraform/service/oqtopus-dev/main.tf
Labels: documentation, chore

#66 fix: fix the path to the .coverage-xxx file
  .github/workflows/python-ci.yaml
Labels: bugfix
