Repository oqtopus-team/oqtopus-cloud, pull requests merged in 2024-09, with the labels that each got.

#5 [Enhancement]: Add git-pr-release
  .github/git-pr-release.erb
  .github/workflows/git-pr-release.yaml
Labels: enhancement

#7 docs: update README.md
  docs/README.md
Labels: documentation

#10 [Docs]: add doi badge
  CITATION.cff
  docs/README.ja.md
  docs/README.md
  docs/en/index.md
  docs/ja/index.md
Labels: documentation

#11 [Docs]: Add release procedure
  docs/en/operation/deployment.md
  docs/ja/operation/deployment.md
Labels: documentation

#12 ci:add labeler
  .github/workflows/labeler.yaml
  .gitmessage
  .vscode/settings.json
  docs/en/developer_guidelines/index.md
  docs/ja/developer_guidelines/index.md
Labels: ci

#13 docs:update openapi.md
  docs/en/developer_guidelines/openapi.md
  docs/ja/architecture/sequence_diagram.md
Labels: documentation

#14 chore: Update CITATION.cff
  CITATION.cff
Labels: chore

#15 docs: update release note config
  .github/git-pr-release.erb
  .github/release.yaml
Labels: documentation

#16 docs: update CITATION.cff
  CITATION.cff
Labels: documentation

#18 docs: update doi badge that is latest one
  docs/README.ja.md
  docs/README.md
  docs/en/index.md
  docs/ja/index.md
Labels: documentation
