Repository oqtopus-team/oqtopus-cloud, pull requests merged in 2024-10, with the labels that each got.

#22 Fix test code typos; QPU → simulator.
  backend/tests/oqtopus_cloud/common/test_model_util.py
  backend/tests/oqtopus_cloud/user/routers/test_devices.py
  backend/tests/oqtopus_cloud/user/routers/test_tasks.py
Labels: chore

#21 docs: add terraform lock document
  docs/en/operation/deployment.md
  docs/ja/operation/deployment.md
Labels: documentation

#25 docs: update `docs/oas`
  docs/oas/provider/openapi.yaml
  docs/oas/user/openapi.yaml
Labels: documentation

#24 chore: update poetry lock
  poetry.lock
Labels: chore

#27 refactor: add cors setting via environent value
  backend/Makefile
  backend/oqtopus_cloud/provider/conf.py
  backend/oqtopus_cloud/provider/lambda_function.py
  backend/oqtopus_cloud/user/conf.py
  backend/oqtopus_cloud/user/lambda_function.py
  poetry.lock
  pyproject.toml
  terraform/service/modules/api-server/main.tf
Labels: chore, refactor

#28 style: disable datamodel-code-generator timestamp
  backend/Makefile
  backend/oqtopus_cloud/provider/schemas/__init__.py
  backend/oqtopus_cloud/provider/schemas/devices.py
  backend/oqtopus_cloud/provider/schemas/error.py
  backend/oqtopus_cloud/provider/schemas/results.py
  backend/oqtopus_cloud/provider/schemas/tasks.py
  backend/oqtopus_cloud/user/schemas/__init__.py
  backend/oqtopus_cloud/user/schemas/devices.py
  backend/oqtopus_cloud/user/schemas/error.py
  backend/oqtopus_cloud/user/schemas/results.py
  backend/oqtopus_cloud/user/schemas/success.py
  backend/oqtopus_cloud/user/schemas/tasks.py
Labels: style

#29 refactor: add lambda module environment variable
  docs/terraform_modules/api-server/README.md
  terraform/service/example-dev/main.tf
  terraform/service/modules/api-server/README.md
  terraform/service/modules/api-server/main.tf
  terraform/service/modules/api-server/variables.tf
Labels: documentation, refactor

#30 docs: add FAQ page
  docs/README.ja.md
  docs/README.md
  docs/en/developer_guidelines/faq.md
  docs/en/index.md
  docs/ja/developer_guidelines/faq.md
  docs/ja/developer_guidelines/index.md
  docs/ja/index.md
  mkdocs.yaml
Labels: documentation

#26 chore: add "created at" and "status" to the response of POST /tasks
  backend/oas/user/openapi.yaml
  backend/oas/user/paths/tasks.yaml
  backend/oas/user/schemas/tasks.yaml
  backend/oqtopus_cloud/user/routers/tasks.py
  backend/oqtopus_cloud/user/schemas/tasks.py
  docs/oas/user/openapi.yaml
Labels: refactor

#31 refactor: Convert code that uses legacy SQLAlchemy API to version 2.0
  backend/oqtopus_cloud/provider/routers/tasks.py
  backend/oqtopus_cloud/user/routers/devices.py
  backend/oqtopus_cloud/user/routers/results.py
  backend/oqtopus_cloud/user/routers/tasks.py
Labels: refactor

#35 docs: add document, how to execute terraform with mfa authentication
  docs/en/developer_guidelines/faq.md
  docs/ja/developer_guidelines/faq.md
  terraform/infrastructure/example-dev/provider.tf
  terraform/infrastructure/example-dev/variables.tf
  terraform/service/example-dev/provider.tf
Labels: documentation

#36 refactor: change of response codes for creating and deleting tasks
  backend/oas/user/openapi.yaml
  backend/oas/user/paths/tasks.yaml
  backend/oqtopus_cloud/user/routers/tasks.py
  backend/tests/oqtopus_cloud/user/routers/test_tasks.py
  docs/oas/user/openapi.yaml
Labels: refactor

#38 ci: update version in `pyproject.toml`
  .github/git-pr-release.erb
  .github/workflows/update_version.yaml
Labels: documentation, ci

#40 docs: fix readthedocs URL
  README.md
Labels: documentation

#44 refactor: delete of internal
  backend/oas/provider/openapi.yaml
  backend/oas/provider/root.yaml
  backend/oqtopus_cloud/provider/routers/devices.py
  backend/oqtopus_cloud/provider/routers/results.py
  backend/oqtopus_cloud/provider/routers/tasks.py
  docs/en/architecture/sequence_diagram.md
  docs/ja/architecture/sequence_diagram.md
  docs/oas/provider/openapi.yaml
  runnbooks/provider/tasks/get-task.yaml
  runnbooks/provider/tasks/get-tasks.yaml
Labels: refactor

#45 refactor: delete of XXX_FETCHED and GET /tasks/unfetched
  backend/db/init/01.schema.sql
  backend/db/init/03.insert_task.sql
  backend/oas/provider/openapi.yaml
  backend/oas/provider/paths/tasks.yaml
  backend/oas/provider/root.yaml
  backend/oas/provider/schemas/tasks.yaml
  backend/oas/redoc-static.html
  backend/oqtopus_cloud/common/models/task.py
  backend/oqtopus_cloud/provider/routers/tasks.py
  backend/oqtopus_cloud/provider/schemas/tasks.py
  backend/oqtopus_cloud/user/routers/tasks.py
  backend/tests/oqtopus_cloud/provider/conftest.py
  backend/tests/oqtopus_cloud/provider/routers/test_tasks.py
  backend/tests/oqtopus_cloud/user/conftest.py
  docs/en/architecture/sequence_diagram.md
  docs/en/architecture/task_state_transition_diagram.md
  docs/ja/architecture/sequence_diagram.md
  docs/ja/architecture/task_state_transition_diagram.md
  docs/oas/provider/openapi.yaml
  docs/sample/architecture/cancel-case-tasks-01.csv
  docs/sample/architecture/cancel-case-tasks-06.csv
  docs/sample/architecture/success-case-tasks-06.csv
  docs/schema/README.md
  docs/schema/devices.md
  docs/schema/results.md
  docs/schema/schema.json
  docs/schema/tasks.md
Labels: refactor, style

#48 docs: fix readthedocs link
  docs/en/index.md
  docs/ja/index.md
Labels: documentation

#49 docs: Fix sequence_diagram.md to match en and jp documents
  docs/en/architecture/sequence_diagram.md
  docs/ja/architecture/sequence_diagram.md
Labels: documentation

#47 chore: resolve trivy alerts
  docs/terraform_modules/api-server/README.md
  docs/terraform_modules/db/README.md
  docs/terraform_modules/management/README.md
  docs/terraform_modules/network/README.md
  docs/terraform_modules/security-group/README.md
  terraform/infrastructure/example-dev/main.tf
  terraform/infrastructure/example-dev/variables.tf
  terraform/infrastructure/modules/db/README.md
  terraform/infrastructure/modules/db/main.tf
  terraform/infrastructure/modules/db/variables.tf
  terraform/infrastructure/modules/management/README.md
  terraform/infrastructure/modules/management/main.tf
  terraform/infrastructure/modules/network/README.md
  terraform/infrastructure/modules/network/main.tf
  terraform/infrastructure/modules/security-group/README.md
  terraform/infrastructure/modules/security-group/main.tf
  terraform/service/modules/api-server/README.md
  terraform/service/modules/api-server/main.tf
Labels: chore

#51 chore: chore/build process uv
  deployment/oqtopus-dev/Makefile
Labels: chore

#50 chore: rename "example-dev" to "oqtopus-dev"
  deployment/oqtopus-dev/Makefile
  docs/asset/aws_system_architecture_diagram_network.drawio.png
  docs/asset/aws_system_architecture_diagram_overview.drawio.png
  docs/en/architecture/aws_system_architecture_diagram.md
  docs/en/developer_guidelines/faq.md
  docs/en/operation/deployment.md
  docs/ja/architecture/aws_system_architecture_diagram.md
  docs/ja/developer_guidelines/faq.md
  docs/ja/operation/deployment.md
  docs/terraform_modules/security-group/README.md
  terraform/infrastructure/modules/security-group/README.md
  terraform/infrastructure/oqtopus-dev/.tflint.hcl
  terraform/infrastructure/oqtopus-dev/Makefile
  terraform/infrastructure/oqtopus-dev/backend.tf
  terraform/infrastructure/oqtopus-dev/main.tf
  terraform/infrastructure/oqtopus-dev/outputs.tf
  terraform/infrastructure/oqtopus-dev/provider.tf
  terraform/infrastructure/oqtopus-dev/variables.tf
  terraform/service/oqtopus-dev/.tflint.hcl
  terraform/service/oqtopus-dev/Makefile
  terraform/service/oqtopus-dev/backend.tf
  terraform/service/oqtopus-dev/main.tf
  terraform/service/oqtopus-dev/outputs.tf
  terraform/service/oqtopus-dev/provider.tf
  terraform/service/oqtopus-dev/variables.tf
Labels: documentation, chore

#54 docs: fix the link for language switching on the top page of the docu…
  mkdocs.yaml
Labels: documentation
