Repository oqtopus-team/oqtopus-cloud, pull requests merged in 2025-04, with the labels that each got.

#180 Feat : terraform prod
  deployment/oqtopus-prod/Makefile
  operation/oqtopus-prod/Makefile
  poetry.lock
  terraform/infrastructure/oqtopus-prod/Makefile
  terraform/infrastructure/oqtopus-prod/backend.tf
  terraform/infrastructure/oqtopus-prod/main.tf
  terraform/infrastructure/oqtopus-prod/outputs.tf
  terraform/infrastructure/oqtopus-prod/provider.tf
  terraform/infrastructure/oqtopus-prod/variables.tf
  terraform/service/modules/lambda-auth/main.tf
  terraform/service/oqtopus-prod/Makefile
  terraform/service/oqtopus-prod/backend.tf
  terraform/service/oqtopus-prod/main.tf
  terraform/service/oqtopus-prod/outputs.tf
  terraform/service/oqtopus-prod/provider.tf
  terraform/service/oqtopus-prod/variables.tf
Labels: feature

#185 feature: Lambda versioning
  deployment/oqtopus-dev/Makefile
Labels: bugfix, chore, feature, refactor

#188 Feat : patch device n qubits
  backend/oas/provider/openapi.yaml
  backend/oas/provider/paths/devices.yaml
  backend/oas/provider/root.yaml
  backend/oas/provider/schemas/devices.yaml
  backend/oqtopus_cloud/provider/routers/devices.py
  backend/oqtopus_cloud/provider/schemas/devices.py
  backend/tests/oqtopus_cloud/provider/routers/test_devices.py
Labels: feature

#196 fix: Fix the issue-195
  backend/oqtopus_cloud/provider/routers/devices.py
Labels: bugfix

#192 fix: update terminology in authentication and signup flow documentation
  docs/en/architecture/frontend_authentication_flow.md
  docs/en/architecture/frontend_signup_signin_flow.md
Labels: enhancement, bugfix, chore

#198 fix: #194 auto deployment failed
  .github/workflows/deployment.yaml
  deployment/oqtopus-dev/Makefile
Labels: bugfix, chore

#200 docs(setup): fix typo in setup command
  docs/en/developer_guidelines/setup.md
Labels: documentation, bugfix

#207 fix: "Update document" failed
  scripts/setup_aqua.sh
Labels: bugfix

#210 feat: #330 prod cd
  .github/workflows/prod-cd.yaml
Labels: bugfix, chore, feature

#211 feat: #209 output diffs.ansi
  .gitignore
  terraform/infrastructure/oqtopus-dev/Makefile
  terraform/infrastructure/oqtopus-prod/Makefile
  terraform/service/oqtopus-dev/Makefile
  terraform/service/oqtopus-prod/Makefile
Labels: chore, feature

#204 feat: Combine poetry setup
  Makefile
  docs/en/developer_guidelines/setup.md
  docs/ja/developer_guidelines/setup.md
Labels: chore, feature
