Repository oqtopus-team/oqtopus-cloud, pull requests merged in 2025-07, with the labels that each got.

#65 feat: Setup migration operation using alembic
  .editorconfig-checker.json
  .github/workflows/editorconfig-review.yaml
  backend/Makefile
  backend/README.md
  backend/alembic.ini
  backend/alembic/env.py
  backend/alembic/script.py.mako
  backend/alembic/versions/20250617__a412606af039__initial.py
  backend/compose.yaml
  backend/oqtopus_cloud/common/model_util.py
  backend/oqtopus_cloud/common/models/__init__.py
  backend/oqtopus_cloud/common/models/announcements.py
  backend/oqtopus_cloud/common/models/base.py
  backend/oqtopus_cloud/common/models/device.py
  backend/oqtopus_cloud/common/models/job.py
  backend/oqtopus_cloud/common/models/quantum_gate.py
  backend/oqtopus_cloud/common/models/user.py
  backend/oqtopus_cloud/common/models/whitelist_user.py
  backend/oqtopus_cloud/common/session.py
  backend/oqtopus_cloud/provider/routers/jobs.py
  backend/oqtopus_cloud/user/routers/jobs.py
  backend/scripts/mig-up.py
  docs/en/developer_guidelines/backend.md
  docs/en/operation/database-migrations.md
  poetry.lock
  pyproject.toml
Labels: bugfix, chore, feature

#266 Bugfix/#265 whitelist not referenced partially
  backend/oqtopus_cloud/admin/routers/users.py
  backend/oqtopus_cloud/lambda_auth/lambda_function.py
  backend/oqtopus_cloud/user_signup/routers/signup.py
  backend/tests/oqtopus_cloud/admin/routers/test_users.py
  backend/tests/oqtopus_cloud/lambda_auth/conftest.py
  backend/tests/oqtopus_cloud/lambda_auth/routers/test_lambda_function.py
  backend/tests/oqtopus_cloud/user_signup/routers/test_user_signup.py
Labels: bugfix, feature

#280 feat: renamed provider APIs `GET /jobs` parameter max_results -> limit
  backend/oas/provider/openapi.yaml
  backend/oas/provider/paths/jobs.yaml
  backend/oqtopus_cloud/provider/routers/jobs.py
  backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
  docs/oas/provider/openapi.yaml
Labels: feature

#287 add API to GET specific user by id
  backend/oas/admin/openapi.yaml
  backend/oas/admin/paths/users.yaml
  backend/oqtopus_cloud/admin/routers/users.py
  backend/tests/oqtopus_cloud/admin/routers/test_users.py
  docs/oas/admin/openapi.yaml
Labels: feature

#286 Duplicate job display bug
  backend/oqtopus_cloud/admin/routers/announcements.py
  backend/oqtopus_cloud/user/routers/announcements.py
  backend/oqtopus_cloud/user/routers/jobs.py
Labels: bugfix
