Repository oqtopus-team/oqtopus-cloud, pull requests merged in 2025-03, with the labels that each got.

#128 fix: add timestamps for device creation and updates in schema conversion
  backend/db/init/01.schema.sql
  backend/oqtopus_cloud/admin/routers/devices.py
Labels: bugfix

#136 Feature/#336 delete unnecessary column users
  backend/db/init/01.schema.sql
  backend/db/init/03.insert_job.sql
  backend/db/init/04.insert_userlist.sql
  backend/oas/admin/openapi.yaml
  backend/oas/admin/schemas/users.yaml
  backend/oqtopus_cloud/admin/routers/users.py
  backend/oqtopus_cloud/admin/schemas/users.py
  backend/oqtopus_cloud/common/models/user.py
  backend/oqtopus_cloud/user_signup/routers/signup.py
  backend/tests/oqtopus_cloud/admin/routers/test_users.py
  backend/tests/oqtopus_cloud/lambda_auth/routers/test_lambda_function.py
  backend/tests/oqtopus_cloud/user/routers/test_api_token.py
  backend/tests/oqtopus_cloud/user_signup/routers/test_mfa_reset_request.py
  backend/tests/oqtopus_cloud/user_signup/routers/test_user_confirm_signup.py
  backend/tests/oqtopus_cloud/user_signup/routers/test_user_signup.py
  docs/oas/admin/openapi.yaml
Labels: bugfix, test

#141 Feat/#305 divided counts as json provider
  backend/oas/provider/openapi.yaml
  backend/oas/provider/schemas/jobs.yaml
  backend/oqtopus_cloud/provider/schemas/jobs.py
  poetry.lock
  pyproject.toml
Labels: feature

#142 Feat : ProviderAPI update jobs' transpiler_info endpoint
  backend/oas/provider/openapi.yaml
  backend/oas/provider/paths/jobs.yaml
  backend/oas/provider/root.yaml
  backend/oas/provider/schemas/jobs.yaml
  backend/oqtopus_cloud/provider/routers/jobs.py
  backend/oqtopus_cloud/provider/schemas/jobs.py
  backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
Labels: feature

#146 feat : OAS change estimation jobs operator coefficient to real
  backend/oas/provider/openapi.yaml
  backend/oas/provider/schemas/jobs.yaml
  backend/oas/user/openapi.yaml
  backend/oas/user/paths/jobs.yaml
  backend/oas/user/schemas/jobs.yaml
  backend/oqtopus_cloud/provider/schemas/jobs.py
  backend/oqtopus_cloud/user/schemas/jobs.py
  backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
Labels: feature

#148 feat: Estimation jobs result has been changed
  backend/oas/provider/openapi.yaml
  backend/oas/provider/schemas/jobs.yaml
  backend/oas/user/openapi.yaml
  backend/oas/user/schemas/jobs.yaml
  backend/oqtopus_cloud/provider/schemas/jobs.py
  backend/oqtopus_cloud/user/schemas/jobs.py
  backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
Labels: feature

#160 fix: pydantic version fixed
  pyproject.toml
Labels: bugfix

#166 feat: #360 add tag resource permission
  terraform/service/modules/api-server/main.tf
  terraform/service/modules/lambda-auth/main.tf
Labels: feature

#169 fix: identity_source line added
  terraform/service/modules/api-server/main.tf
Labels: bugfix

#127 Docs/#332 authentication flow diagrams
  docs/en/architecture/aws_system_architecture_diagram.md
  docs/en/architecture/frontend_authentication_flow.md
  docs/en/architecture/frontend_signup_signin_flow.md
  terraform/service/oqtopus-dev/main.tf
Labels: documentation

#131 feat: DB jobs table column order
  backend/db/init/01.schema.sql
Labels: feature

#170 feat: Add a process to delete S3 resources when SSE job is deleted.
  backend/oqtopus_cloud/user/routers/jobs.py
  backend/tests/oqtopus_cloud/user/routers/test_jobs.py
Labels: feature

#165 fix: add user suspend
  backend/oqtopus_cloud/lambda_auth/lambda_function.py
  backend/tests/oqtopus_cloud/lambda_auth/routers/test_lambda_function.py
Labels: bugfix

#173 Update README to include Slack workspace link and improve formatting
  README.md
  docs/asset/oqtopus-logo.png
  docs/en/index.md
  docs/ja/index.md
Labels: documentation

#162 feat: Create update poetry.lock action
  .github/workflows/update-poetry-lock.yaml
Labels: feature

#163 feat: add slack bot on deploy
  .github/workflows/deployment.yaml
Labels: chore, feature

#164 chore: python version fixed
  docs/en/developer_guidelines/setup.md
Labels: documentation, chore

#133 feature: Credential scan added
  Makefile
  aqua.yaml
  docs/en/developer_guidelines/setup.md
  docs/ja/developer_guidelines/setup.md
  lefthook.yml
  scripts/setup_hooks.sh
Labels: bugfix, chore, feature, refactor

#175 feat: TranspileResult JSON
  backend/oas/provider/openapi.yaml
  backend/oas/provider/schemas/jobs.yaml
  backend/oas/user/openapi.yaml
  backend/oas/user/schemas/jobs.yaml
  backend/oqtopus_cloud/provider/schemas/jobs.py
  backend/oqtopus_cloud/user/schemas/jobs.py
  backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
Labels: feature

#179 feat: improved notification text
  .github/workflows/deployment.yaml
Labels: feature

#177 fix: add git configs
  .github/workflows/update-poetry-lock.yaml
Labels: bugfix
