Repository oqtopus-team/oqtopus-cloud, pull requests merged in 2025-02, with the labels that each got.

#82 docs: update oas
  docs/oas/provider/openapi.yaml
  docs/oas/user/openapi.yaml
Labels: documentation

#83 fix: use `--output-datetime-class` option
  backend/Makefile
  backend/oas/provider/openapi.yaml
  backend/oas/provider/schemas/jobs.yaml
  backend/oqtopus_cloud/user/schemas/jobs.py
  docs/oas/provider/openapi.yaml
  poetry.lock
Labels: bugfix

#89 feat: Backend responses' datetime explicitly localized
  backend/Makefile
  backend/oqtopus_cloud/provider/routers/jobs.py
  backend/oqtopus_cloud/provider/schemas/devices.py
  backend/oqtopus_cloud/provider/schemas/jobs.py
  backend/oqtopus_cloud/user/routers/devices.py
  backend/oqtopus_cloud/user/routers/jobs.py
  backend/oqtopus_cloud/user/schemas/devices.py
  backend/oqtopus_cloud/user/schemas/jobs.py
  backend/tests/oqtopus_cloud/provider/routers/test_devices.py
  backend/tests/oqtopus_cloud/user/conftest.py
  backend/tests/oqtopus_cloud/user/routers/test_devices.py
  backend/tests/oqtopus_cloud/user/routers/test_jobs.py
  poetry.lock
  pyproject.toml
Labels: feature

#90 feat: Provider API security auth
  backend/oas/provider/openapi.yaml
  backend/oas/provider/paths/devices.yaml
  backend/oas/provider/paths/jobs.yaml
  backend/oas/provider/root.yaml
  docs/oas/provider/openapi.yaml
Labels: feature

#87 fix: `job_info` json format
  backend/db/init/03.insert_job.sql
Labels: bugfix

#88 docs: add run scripts
  backend/README.md
Labels: documentation

#93 bugs: Provider API: Remove too restrictive guard for updating job_info
  backend/oqtopus_cloud/provider/routers/jobs.py
  backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
Labels: bug

#74 feat: #203 #204 add admin page API
  .github/workflows/python-ci.yaml
  Makefile
  backend/Makefile
  backend/db/init/01.schema.sql
  backend/db/init/04.insert_userlist.sql
  backend/db/init/05.insert_whitelist.sql
  backend/oas/Makefile
  backend/oas/admin/openapi.yaml
  backend/oas/admin/paths/users.yaml
  backend/oas/admin/paths/whitelist_users.yaml
  backend/oas/admin/root.yaml
  backend/oas/admin/schemas/error.yaml
  backend/oas/admin/schemas/security.yaml
  backend/oas/admin/schemas/success.yaml
  backend/oas/admin/schemas/users.yaml
  backend/oas/admin/schemas/whitelist_users.yaml
  backend/oqtopus_cloud/admin/__init__.py
  backend/oqtopus_cloud/admin/conf.py
  backend/oqtopus_cloud/admin/lambda_function.py
  backend/oqtopus_cloud/admin/middleware.py
  backend/oqtopus_cloud/admin/routers/__init__.py
  backend/oqtopus_cloud/admin/routers/users.py
  backend/oqtopus_cloud/admin/routers/whitelist_users.py
  backend/oqtopus_cloud/admin/schemas/__init__.py
  backend/oqtopus_cloud/admin/schemas/error.py
  backend/oqtopus_cloud/admin/schemas/errors.py
  backend/oqtopus_cloud/admin/schemas/success.py
  backend/oqtopus_cloud/admin/schemas/users.py
  backend/oqtopus_cloud/admin/schemas/whitelist_users.py
  backend/oqtopus_cloud/common/models/__init__.py
  backend/oqtopus_cloud/common/models/job.py
  backend/oqtopus_cloud/common/models/user.py
  backend/oqtopus_cloud/common/models/whitelist_user.py
  backend/tests/oqtopus_cloud/admin/__init__.py
  backend/tests/oqtopus_cloud/admin/conftest.py
  backend/tests/oqtopus_cloud/admin/routers/__init__.py
  backend/tests/oqtopus_cloud/admin/routers/test_usres.py
  backend/tests/oqtopus_cloud/admin/routers/test_whitelist_usres.py
  deployment/oqtopus-dev/Makefile
  terraform/infrastructure/oqtopus-dev/main.tf
  terraform/service/oqtopus-dev/main.tf
Labels: bugfix, feature, refactor

#96 feat: #307 update document ci
  .github/workflows/update-document.yaml
Labels: bugfix, chore, feature

#97 fix: job info message and result
  backend/oqtopus_cloud/provider/routers/jobs.py
  backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
Labels: bug, bugfix

#98 Feature/#291 signup trigger
  .github/workflows/python-ci.yaml
  backend/Makefile
  backend/oas/Makefile
  backend/oas/admin/root.yaml
  backend/oas/user_signup/openapi.yaml
  backend/oas/user_signup/paths/confirm_signup.yaml
  backend/oas/user_signup/paths/mfa_reset_request.yaml
  backend/oas/user_signup/paths/signup.yaml
  backend/oas/user_signup/root.yaml
  backend/oas/user_signup/schemas/confirm_signup.yaml
  backend/oas/user_signup/schemas/error.yaml
  backend/oas/user_signup/schemas/mfa_reset_request.yaml
  backend/oas/user_signup/schemas/security.yaml
  backend/oas/user_signup/schemas/signup.yaml
  backend/oqtopus_cloud/user_signup/__init__.py
  backend/oqtopus_cloud/user_signup/conf.py
  backend/oqtopus_cloud/user_signup/lambda_function.py
  backend/oqtopus_cloud/user_signup/middleware.py
  backend/oqtopus_cloud/user_signup/routers/__init__.py
  backend/oqtopus_cloud/user_signup/routers/confirm_signup.py
  backend/oqtopus_cloud/user_signup/routers/mfa_reset_request.py
  backend/oqtopus_cloud/user_signup/routers/signup.py
  backend/oqtopus_cloud/user_signup/schemas/__init__.py
  backend/oqtopus_cloud/user_signup/schemas/confirm_signup.py
  backend/oqtopus_cloud/user_signup/schemas/error.py
  backend/oqtopus_cloud/user_signup/schemas/errors.py
  backend/oqtopus_cloud/user_signup/schemas/mfa_reset_request.py
  backend/oqtopus_cloud/user_signup/schemas/signup.py
  backend/tests/oqtopus_cloud/lambda_auth/routers/test_lambda_function.py
  backend/tests/oqtopus_cloud/user_signup/__init__.py
  backend/tests/oqtopus_cloud/user_signup/conftest.py
  backend/tests/oqtopus_cloud/user_signup/routers/__init__.py
  backend/tests/oqtopus_cloud/user_signup/routers/test_mfa_reset_request.py
  backend/tests/oqtopus_cloud/user_signup/routers/test_user_confirm_signup.py
  backend/tests/oqtopus_cloud/user_signup/routers/test_user_signup.py
  deployment/oqtopus-dev/Makefile
  poetry.lock
  pyproject.toml
Labels: ci, bugfix, chore, feature, refactor, style, test

#95 feat: Provider API: Add nullable mark to each property of object fields in OAS
  backend/oas/admin/openapi.yaml
  backend/oas/provider/openapi.yaml
  backend/oas/provider/paths/devices.yaml
  backend/oas/provider/paths/hello.yaml
  backend/oas/provider/paths/jobs.yaml
  backend/oas/provider/root.yaml
  backend/oas/provider/schemas/devices.yaml
  backend/oas/provider/schemas/error.yaml
  backend/oas/provider/schemas/jobs.yaml
  backend/oas/user_signup/openapi.yaml
  backend/oqtopus_cloud/provider/routers/jobs.py
  backend/oqtopus_cloud/provider/schemas/devices.py
  backend/oqtopus_cloud/provider/schemas/jobs.py
  backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
  docs/oas/provider/openapi.yaml
  docs/oas/user/openapi.yaml
Labels: bugfix, feature

#100 fix: Add security tag in patch job info
  backend/oas/provider/openapi.yaml
  backend/oas/provider/paths/jobs.yaml
  docs/oas/provider/openapi.yaml
Labels: bugfix

#101 fix: Add nullable to EstimationResult
  backend/oas/provider/openapi.yaml
  backend/oas/provider/schemas/jobs.yaml
  backend/oqtopus_cloud/provider/schemas/jobs.py
  docs/oas/provider/openapi.yaml
Labels: bugfix

#103 feat: Set the datetime when update job status
  backend/oqtopus_cloud/provider/routers/jobs.py
  backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
Labels: feature

#114 fix: ProviderAPI: Update execution time
  backend/oqtopus_cloud/provider/routers/jobs.py
  backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
Labels: bugfix

#85 feat: #286 revise PATCH /devices/{device_id}
  .github/workflows/python-ci.yaml
  backend/Makefile
  backend/oas/provider/openapi.yaml
  backend/oas/provider/paths/devices.yaml
  backend/oas/provider/root.yaml
  backend/oas/provider/schemas/devices.yaml
  backend/oqtopus_cloud/provider/routers/devices.py
  backend/oqtopus_cloud/provider/schemas/devices.py
  backend/oqtopus_cloud/worker/pending_jobs_updater/conf.py
  backend/oqtopus_cloud/worker/pending_jobs_updater/lambda_function.py
  backend/tests/oqtopus_cloud/provider/routers/test_devices.py
  backend/tests/oqtopus_cloud/worker/pending_jobs_updater/conftest.py
  backend/tests/oqtopus_cloud/worker/pending_jobs_updater/test_pending_jobs_updater.py
  deployment/oqtopus-dev/Makefile
  docs/oas/provider/openapi.yaml
  docs/terraform_modules/security-group/README.md
  terraform/infrastructure/modules/security-group/README.md
  terraform/service/modules/worker/.tflint.hcl
  terraform/service/modules/worker/README.md
  terraform/service/modules/worker/main.tf
  terraform/service/modules/worker/outputs.tf
  terraform/service/modules/worker/provider.tf
  terraform/service/modules/worker/variables.tf
  terraform/service/oqtopus-dev/main.tf
Labels: documentation, ci, bugfix, chore, feature, refactor, test

#106 Feature/#325 unit test
  backend/oas/admin/openapi.yaml
  backend/oas/admin/paths/whitelist_users.yaml
  backend/oqtopus_cloud/admin/routers/users.py
  backend/oqtopus_cloud/admin/routers/whitelist_users.py
  backend/oqtopus_cloud/lambda_auth/lambda_function.py
  backend/oqtopus_cloud/user_signup/routers/confirm_signup.py
  backend/oqtopus_cloud/user_signup/routers/mfa_reset_request.py
  backend/oqtopus_cloud/user_signup/routers/signup.py
  backend/tests/oqtopus_cloud/admin/routers/test_users.py
  backend/tests/oqtopus_cloud/admin/routers/test_whitelist_users.py
  backend/tests/oqtopus_cloud/lambda_auth/conftest.py
  backend/tests/oqtopus_cloud/lambda_auth/routers/test_lambda_function.py
  backend/tests/oqtopus_cloud/user/routers/test_api_token.py
  backend/tests/oqtopus_cloud/user_signup/conftest.py
  backend/tests/oqtopus_cloud/user_signup/routers/test_mfa_reset_request.py
  backend/tests/oqtopus_cloud/user_signup/routers/test_user_confirm_signup.py
  backend/tests/oqtopus_cloud/user_signup/routers/test_user_signup.py
Labels: bugfix, test

#117 Feature/#209 admin device page
  backend/oas/admin/openapi.yaml
  backend/oas/admin/paths/devices.yaml
  backend/oas/admin/root.yaml
  backend/oas/admin/schemas/devices.yaml
  backend/oqtopus_cloud/admin/lambda_function.py
  backend/oqtopus_cloud/admin/routers/devices.py
  backend/oqtopus_cloud/admin/routers/users.py
  backend/oqtopus_cloud/admin/schemas/devices.py
  backend/oqtopus_cloud/common/models/device.py
  backend/tests/oqtopus_cloud/admin/routers/test_devices.py
  backend/tests/oqtopus_cloud/admin/routers/test_users.py
Labels: bugfix, feature, refactor

#119 Feature/#288 add SSE and MP manual
  backend/oas/provider/openapi.yaml
  backend/oas/provider/paths/jobs.yaml
  backend/oas/provider/root.yaml
  backend/oas/provider/schemas/jobs.yaml
  backend/oas/user/openapi.yaml
  backend/oas/user/paths/jobs.yaml
  backend/oas/user/root.yaml
  backend/oas/user/schemas/jobs.yaml
  backend/oqtopus_cloud/common/models/job.py
  backend/oqtopus_cloud/provider/routers/jobs.py
  backend/oqtopus_cloud/provider/schemas/jobs.py
  backend/oqtopus_cloud/user/routers/jobs.py
  backend/oqtopus_cloud/user/schemas/jobs.py
  backend/tests/oqtopus_cloud/provider/conftest.py
  backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
  backend/tests/oqtopus_cloud/user/conftest.py
  backend/tests/oqtopus_cloud/user/routers/test_jobs.py
  poetry.lock
  pyproject.toml
Labels: bugfix, feature

#122 fix: handle None input in ensure_timezone function
  backend/oqtopus_cloud/admin/routers/devices.py
Labels: bugfix

#123 fix: streamline authorization policy generation in lambda_handler
  backend/oqtopus_cloud/lambda_auth/lambda_function.py
Labels: bugfix

#125 refactor: Modify casing of OAS operation id
  backend/oas/admin/openapi.yaml
  backend/oas/admin/paths/devices.yaml
  backend/oas/admin/paths/users.yaml
  backend/oas/admin/paths/whitelist_users.yaml
  backend/oas/provider/openapi.yaml
  backend/oas/provider/paths/devices.yaml
  backend/oas/provider/paths/hello.yaml
  backend/oas/provider/paths/jobs.yaml
  backend/oas/provider/root.yaml
  backend/oas/user/openapi.yaml
  backend/oas/user/paths/api-token.yaml
  backend/oas/user/paths/devices.yaml
  backend/oas/user/paths/jobs.yaml
  backend/oas/user/root.yaml
  backend/oas/user_signup/openapi.yaml
  backend/oas/user_signup/paths/confirm_signup.yaml
  backend/oas/user_signup/paths/mfa_reset_request.yaml
  docs/oas/admin/openapi.yaml
  docs/oas/provider/openapi.yaml
  docs/oas/user/openapi.yaml
Labels: refactor
