Repository oqtopus-team/oqtopus-cloud, pull requests merged in 2025-06, with the labels that each got.

#227 feat: create actionlint workflow
  .github/workflows/actionlint.yaml
Labels: chore, feature

#224 feat: add editorconfig-checker and reviewdog
  .github/workflows/editorconfig-review.yaml
  scripts/ecc_converter.py
Labels: bugfix, chore, feature, refactor

#236 fix: actionlint error fixed
  .github/workflows/deployment.yaml
  .github/workflows/editorconfig-review.yaml
  .github/workflows/labeler.yaml
  .github/workflows/prod-cd.yaml
  .github/workflows/tflint.yaml
  .github/workflows/update-document.yaml
  .github/workflows/update-poetry-lock.yaml
  .github/workflows/update_version.yaml
Labels: bugfix

#244 feat: make editorconfig-checker ignore markdown
  .github/workflows/editorconfig-review.yaml
Labels: feature

#240 Feat : Abstract Storage
  backend/Makefile
  backend/compose.yaml
  backend/oqtopus_cloud/admin/routers/announcements.py
  backend/oqtopus_cloud/common/storages/__init__.py
  backend/oqtopus_cloud/common/storages/abstract_storage.py
  backend/oqtopus_cloud/common/storages/fsspec_storage.py
  backend/oqtopus_cloud/common/storages/storage_utils.py
  backend/oqtopus_cloud/provider/routers/jobs.py
  backend/oqtopus_cloud/user/routers/jobs.py
  backend/stubs/fsspec/__init__.pyi
  backend/stubs/fsspec/fsspec.pyi
  backend/tests/oqtopus_cloud/provider/conftest.py
  backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
  backend/tests/oqtopus_cloud/user/conftest.py
  backend/tests/oqtopus_cloud/user/routers/test_jobs.py
  docs/en/developer_guidelines/backend.md
  docs/terraform_modules/api-server/README.md
  poetry.lock
  pyproject.toml
  terraform/service/modules/api-server/README.md
  terraform/service/modules/api-server/main.tf
  terraform/service/modules/api-server/variables.tf
  terraform/service/oqtopus-dev/main.tf
Labels: feature
