Repository oqtopus-team/oqtopus-cloud, pull requests merged in 2025-01, with the labels that each got.

#67 chore: fix zip command
  deployment/oqtopus-dev/Makefile
Labels: chore

#70 refactor: unify OpenAPI responses from 'details' or 'message' to 'message'
  backend/oas/provider/openapi.yaml
  backend/oas/provider/paths/devices.yaml
  backend/oas/provider/paths/hello.yaml
  backend/oas/provider/paths/jobs.yaml
  backend/oas/provider/schemas/error.yaml
  backend/oas/user/openapi.yaml
  backend/oas/user/paths/devices.yaml
  backend/oas/user/paths/jobs.yaml
  backend/oas/user/schemas/error.yaml
  backend/oqtopus_cloud/provider/routers/devices.py
  backend/oqtopus_cloud/provider/routers/jobs.py
  backend/oqtopus_cloud/provider/schemas/error.py
  backend/oqtopus_cloud/provider/schemas/errors.py
  backend/oqtopus_cloud/user/routers/devices.py
  backend/oqtopus_cloud/user/routers/jobs.py
  backend/oqtopus_cloud/user/schemas/error.py
  backend/oqtopus_cloud/user/schemas/errors.py
  backend/tests/oqtopus_cloud/user/routers/test_jobs.py
Labels: chore, refactor, test

#71 feat: Lambda SnapStart enabled (from: None to: PublishedVersions)
  terraform/service/modules/api-server/main.tf
Labels: feature

#72 chore: update org from "example" to "oqtopus"
  docs/en/operation/deployment.md
  docs/ja/operation/deployment.md
Labels: chore

#69 feat: #282 add datetimes
  backend/db/init/01.schema.sql
  backend/db/init/03.insert_job.sql
  backend/oas/provider/openapi.yaml
  backend/oas/provider/schemas/jobs.yaml
  backend/oas/user/openapi.yaml
  backend/oas/user/schemas/jobs.yaml
  backend/oqtopus_cloud/common/models/job.py
  backend/oqtopus_cloud/provider/routers/jobs.py
  backend/oqtopus_cloud/provider/schemas/jobs.py
  backend/oqtopus_cloud/user/routers/jobs.py
  backend/oqtopus_cloud/user/schemas/jobs.py
  backend/tests/oqtopus_cloud/provider/routers/test_jobs.py
  backend/tests/oqtopus_cloud/user/routers/test_jobs.py
  operation/db/init.sql
Labels: feature

#76 docs: add @katsujukou to codeowners
  .github/CODEOWNERS
Labels: documentation

#75 feat: update mkdocs-static-i18n
  poetry.lock
  pyproject.toml
Labels: feature

#80 fix: #78 coverage action error
  .github/workflows/python-ci.yaml
Labels: bugfix
